import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';
import { colors } from './tokens';

export const THEME = {
  light: {
    background: colors.paperWhite,
    foreground: colors.carbon,
    card: colors.paperWhite,
    cardForeground: colors.carbon,
    popover: colors.paperWhite,
    popoverForeground: colors.carbon,
    primary: colors.lavender,
    primaryForeground: colors.paperWhite,
    secondary: colors.mist,
    secondaryForeground: colors.carbon,
    muted: colors.mist,
    mutedForeground: colors.ash,
    accent: colors.linen,
    accentForeground: colors.carbon,
    destructive: colors.ember,
    border: colors.fog,
    input: colors.fog,
    ring: colors.lavender,
    radius: '1rem',
    chart1: colors.sky,
    chart2: colors.mint,
    chart3: colors.amber,
    chart4: colors.iris,
    chart5: colors.magenta,
  },
  dark: {
    background: '#12131a',
    foreground: '#fafafa',
    card: '#181925',
    cardForeground: '#fafafa',
    popover: '#181925',
    popoverForeground: '#fafafa',
    primary: colors.lavender,
    primaryForeground: colors.paperWhite,
    secondary: '#222333',
    secondaryForeground: '#fafafa',
    muted: '#222333',
    mutedForeground: colors.ash,
    accent: '#1c1d28',
    accentForeground: '#fafafa',
    destructive: colors.ember,
    border: '#2a2b38',
    input: '#2a2b38',
    ring: colors.lavender,
    radius: '1rem',
    chart1: colors.sky,
    chart2: colors.mint,
    chart3: colors.amber,
    chart4: colors.iris,
    chart5: colors.magenta,
  },
};

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
